// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8jv3mD0n6HcX4g2ZZyQoL0GO_MSGBpMw',
    appId: '1:507693682170:web:9cc06d60dbc08cc5b12843',
    messagingSenderId: '507693682170',
    projectId: 'spliteasy-8340f',
    authDomain: 'spliteasy-8340f.firebaseapp.com',
    storageBucket: 'spliteasy-8340f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSoDLrL02thaCEario1tTjnwHAY6VEUBA',
    appId: '1:507693682170:android:74d3732b97c16406b12843',
    messagingSenderId: '507693682170',
    projectId: 'spliteasy-8340f',
    storageBucket: 'spliteasy-8340f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvt0nz9CZxmLQZm6hU7lPvakur9HWt-EE',
    appId: '1:507693682170:ios:252fd407675fe640b12843',
    messagingSenderId: '507693682170',
    projectId: 'spliteasy-8340f',
    storageBucket: 'spliteasy-8340f.firebasestorage.app',
    iosBundleId: 'com.example.splitEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvt0nz9CZxmLQZm6hU7lPvakur9HWt-EE',
    appId: '1:507693682170:ios:252fd407675fe640b12843',
    messagingSenderId: '507693682170',
    projectId: 'spliteasy-8340f',
    storageBucket: 'spliteasy-8340f.firebasestorage.app',
    iosBundleId: 'com.example.splitEasy',
  );
}
